### ISSUE TITLE
helm chart / dockerimage

### ISSUE THREAD

**Issue by DracoBlue** [syseleven/shared-secrets#13]
Hello @yahesh,

is a dockerimage or helm chart in the works or appricated?

Best regards

Jan

**Comment by yahesh** [comment]
@DracoBlue Not from my side, but @macwinnie seems to have built something in #11. If he provided his current dockercompose file I could build something from there.

**Comment by macwinnie** [comment]
Hi @yahesh,

I'm not working with `docker-compose` directly – but it's as simple as this:

```yml
---

version: '3'

services:

  database:
    container_name: shared-secrets_db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: *******
      MYSQL_USER: shared-secrets
      MYSQL_PASSWORD: *******
    network_mode: host

  shared-secrets:
    container_name: shared-secrets
    image:  devopsansiblede/apache:latest
    restart: always
    environment:
      APACHE_ADDITIONAL: >
        <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase   /

            # prevent access to certain locations
            RewriteRule ^\.git(\/.*)?$    - [R=404,L]
            RewriteRule ^\.gitattributes$ - [R=404,L]
            RewriteRule ^\.gitignore$     - [R=404,L]
            RewriteRule ^\.htaccess$      - [R=404,L]
            RewriteRule ^actions(\/.*)?$  - [R=404,L]
            RewriteRule ^CHANGELOG\.md$   - [R=404,L]
            RewriteRule ^config(\/.*)?$   - [R=404,L]
            RewriteRule ^ENCRYPTION\.md$  - [R=404,L]
            RewriteRule ^lib(\/.*)?$      - [R=404,L]
            RewriteRule ^LICENSE$         - [R=404,L]
            RewriteRule ^pages(\/.*)?$    - [R=404,L]
            RewriteRule ^README\.md$      - [R=404,L]
            RewriteRule ^router\.php$     - [R=404,L]
            RewriteRule ^template(\/.*)?$ - [R=404,L]

            # single entrypoint
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule . /index.php [L]
        </IfModule>
    volumes:
      - ./html:/var/www/html
    network_mode: host
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 50m

...
```

The `./html` directory is a clone of the current repository.

The compose file above lets the container publish the web app directly. When a proxy is needed, I regularly use Træfik. 

You'll have to secure your database since that docker compose file would fully publish it.

If you'd use a NGINX instead of an Apache, you'd have to adjust the information by the whole config within the project Readme.

Best
Macwinnie
